[meta]
folder = "results/variable_phaseonium"
description = " "

[system]
type = "Phaseonium"  # System type: Phaseonium, Qubit
ndims = 3
coherences = [0.785398163, 3.141592653, 6.283185307]  # System coherences (in radians)
excitations = 1  # Number of excitations to separate ground and excited states
frequency = 1.0  # System frequency
thermalization_time = [0.5, 100.0]
# gamma = 0.1  # System decay rate

[environment]
g = 1.0  # Environment energy level splitting
J = 1.0  # System-Environment coupling
gamma = 1.0  # Environment decay rate

[ancilla]
type = "Qubit"
ndims = 2
excitations = 1
chains = [1, 2, 4]  # Number of ancilla chains
layers = [1, 2, 10]  # Number of ancillas per chain
frequency = 1.0  # Ancillas frequency
g = 1.0  # Ancilla-Ancilla interaction strength
intra_interaction_time =  0.785398163 # 1.570796326  # Ancilla-Ancilla interaction time
collision_time = 0.031415926  # Ancilla-System interaction time

[thermometer]
T_min = 0.002  # Minimum temperature
T_max = 2.0  # Maximum temperature
accuracy = 100  # Number of temperatures to scan
